# Generated by Django 6.0.4 on 2026-04-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Cancha')),
                ('tipo_superficie', models.CharField(max_length=50, verbose_name='Tipo de Superficie')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de personas')),
                ('esta_disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
            },
        ),
    ]
