# El Alias vincula una URL con una carpeta física
Alias /admin "/var/www/html/administrativo"

<Directory "/var/www/html/administrativo">
    # Permite ver los archivos y seguir enlaces
    Options Indexes FollowSymLinks
    # Permite que el servidor lea los archivos
    AllowOverride None
    Require all granted
</Directory>