# Si el usuario escribe /estudiantes, verá la carpeta alumnos
Alias /estudiantes "/var/www/html/alumnos"

<Directory "/var/www/html/alumnos">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>