# Alias para la sección de profesores
Alias /profesores "/var/www/html/docentes"

<Directory "/var/www/html/docentes">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>