# 1. Imagen base de Ubuntu
FROM ubuntu:24.04

# 2. Evitar que Ubuntu nos haga preguntas durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# 3. Actualizar e instalar Apache y limpiar caché en un solo paso para que sea ligero
RUN apt-get update && apt-get install -y \
    apache2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 4. Copiar tus carpetas de contenido a la ruta de Apache
COPY ./administrativo /var/www/html/administrativo
COPY ./alumnos /var/www/html/alumnos
COPY ./docentes /var/www/html/docentes
COPY ./imagenes /var/www/html/imagenes

# 5. Copiar tus archivos de configuración personalizada
# Estos archivos deben tener la instrucción "Alias" adentro
COPY ./administrativo.conf /etc/apache2/sites-available/
COPY ./alumnos.conf /etc/apache2/sites-available/
COPY ./docentes.conf /etc/apache2/sites-available/

# 6. Activar tus sitios (opcional, dependiendo de cómo configuraste los .conf)
# ACTIVAR LOS SITIOS Y RECARGAR APACHE
RUN a2ensite administrativo.conf && \
    a2ensite alumnos.conf && \
    a2ensite docentes.conf

# 7. Exponer el puerto 80 para la web
EXPOSE 80

# 8. Comando para que Apache corra siempre en primer plano
CMD ["apachectl", "-D", "FOREGROUND"]